// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPR0MAeGNjw1jAuPZbeA3zQUxQ4sGh0h0',
    appId: '1:599927475107:web:606712a995dad45d962816',
    messagingSenderId: '599927475107',
    projectId: 'fir-25-3001a',
    authDomain: 'fir-25-3001a.firebaseapp.com',
    storageBucket: 'fir-25-3001a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTqE3rWtNsAlJAgZ7UGsHnxlFr7QXJ8Q',
    appId: '1:599927475107:android:1bf72234881a6fac962816',
    messagingSenderId: '599927475107',
    projectId: 'fir-25-3001a',
    storageBucket: 'fir-25-3001a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwIz2m0EG1W6QHVVuCD3375xND2RvmgA8',
    appId: '1:599927475107:ios:907d255677a9ea21962816',
    messagingSenderId: '599927475107',
    projectId: 'fir-25-3001a',
    storageBucket: 'fir-25-3001a.appspot.com',
    iosBundleId: 'com.example.firebaselog2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwIz2m0EG1W6QHVVuCD3375xND2RvmgA8',
    appId: '1:599927475107:ios:e7c3ee26515bb80f962816',
    messagingSenderId: '599927475107',
    projectId: 'fir-25-3001a',
    storageBucket: 'fir-25-3001a.appspot.com',
    iosBundleId: 'com.example.firebaselog2.RunnerTests',
  );
}
